package wiring

import (
	"strings"

	"github.com/IVIR3zaM/Cairn/internal/config"
)

// github generates a GitHub Actions workflow at .github/workflows/cairn.yml that installs
// Cairn and runs each configured CI job (cfg.CI.Jobs, typically just `verify`) — so CI and
// the local hook share the one contract. It self-registers; adding another provider (GitLab,
// Circle) is a sibling ci_<name>.go, no edit here.
func init() {
	register("github", github{})
}

type github struct{}

func (github) Workflow(cfg *config.Config) (string, []byte) {
	jobs := cfg.CI.Jobs
	if len(jobs) == 0 {
		jobs = []string{"verify"}
	}
	var b strings.Builder
	b.WriteString("# Generated by Cairn from cairn.yaml (ci.provider: github). Re-run `cairn init` to update.\n")
	b.WriteString("name: cairn\n")
	b.WriteString("on: [push, pull_request]\n")
	b.WriteString("jobs:\n")
	b.WriteString("  cairn:\n")
	b.WriteString("    runs-on: ubuntu-latest\n")
	b.WriteString("    steps:\n")
	b.WriteString("      - uses: actions/checkout@v4\n")
	b.WriteString("      - uses: actions/setup-go@v5\n")
	b.WriteString("        with:\n")
	b.WriteString("          go-version: stable\n")
	b.WriteString("      - run: go install github.com/IVIR3zaM/Cairn/cmd/cairn@latest\n")
	for _, job := range jobs {
		b.WriteString("      - run: cairn " + job + "\n")
	}
	return ".github/workflows/cairn.yml", []byte(b.String())
}
