package wiring

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/IVIR3zaM/Cairn/internal/config"
)

// HooksDir is the tracked directory the installed git hooks live in. It is committed to the
// repo and wired via `git config core.hooksPath`, so every clone shares the same hooks
// without each developer copying scripts into .git/hooks (which is untracked).
const HooksDir = ".cairn/hooks"

// InstallHooks writes the git hooks described by cfg.Hooks into the repo rooted at dir and
// points git at them via core.hooksPath. Each hook script shells out to the configured cairn
// jobs, so the same `cairn verify` runs locally and in CI (ADR-005). It returns the git hook
// names installed (e.g. "pre-commit"), and is idempotent: re-running rewrites identical
// executable scripts and re-sets core.hooksPath (a no-op when already set).
func InstallHooks(dir string, cfg *config.Config) ([]string, error) {
	// Map each config hook list to its git hook filename. commit-msg receives the message
	// file path as $1, which the script forwards so the job can lint it.
	specs := []struct {
		git  string
		jobs []string
	}{
		{"pre-commit", cfg.Hooks.PreCommit},
		{"commit-msg", cfg.Hooks.CommitMsg},
		{"pre-push", cfg.Hooks.PrePush},
	}

	full := filepath.Join(dir, HooksDir)
	if err := os.MkdirAll(full, 0o755); err != nil {
		return nil, err
	}

	var installed []string
	for _, s := range specs {
		if len(s.jobs) == 0 {
			continue
		}
		path := filepath.Join(full, s.git)
		if err := os.WriteFile(path, []byte(hookScript(s.git, s.jobs)), 0o755); err != nil {
			return nil, err
		}
		// WriteFile preserves an existing file's mode, so chmod explicitly to keep the script
		// executable on an idempotent re-install.
		if err := os.Chmod(path, 0o755); err != nil {
			return nil, err
		}
		installed = append(installed, s.git)
	}

	if err := setHooksPath(dir); err != nil {
		return nil, err
	}
	return installed, nil
}

// hookScript renders a POSIX-sh hook that runs each cairn job in order, aborting on the first
// failure (set -e). The commit-msg hook forwards its arguments ($@, the message file path) so
// the job can read the proposed message.
func hookScript(gitHook string, jobs []string) string {
	args := ""
	if gitHook == "commit-msg" {
		args = ` "$@"`
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by Cairn from cairn.yaml (hooks." + strings.ReplaceAll(gitHook, "-", "_") + "). Re-run `cairn init` to update.\n")
	b.WriteString("set -e\n")
	for _, job := range jobs {
		b.WriteString("cairn " + job + args + "\n")
	}
	return b.String()
}

// setHooksPath points git at the tracked hooks dir. Shelling out to git keeps Cairn from
// reimplementing config parsing, and is idempotent.
func setHooksPath(dir string) error {
	cmd := exec.Command("git", "config", "core.hooksPath", HooksDir)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git config core.hooksPath: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
